[workspace]
resolver = "2"
version = "0.1.1"
authors = [
	"michaelangeloio"
]

members = [
    "crates/does-it-throw",
    "crates/does-it-throw-wasm"
]

exclude = [
    "docs/examples/quickstart/rust"
]

[profile.release]
debug = false

[profile.bench]
debug = true
