[workspace]
resolver = "2"

[package]
name = "does-it-throw-workspace"
version = "0.1.1"

members = [
    "crates/does-it-throw",
    "crates/does-it-throw-wasm"
]

exclude = [
    "docs/examples/quickstart/rust"
]

[profile.release]
debug = false

[profile.bench]
debug = true
