name: Release NPM

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Bun
        uses: oven-sh/setup-bun@a1800f471a0bc25cddac36bb13e6f436ddf341d7

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@0d096b08b4e5a7de8c28de67e11e945404e9eefa
        with:
          version: 'latest'

      - name: Install dependencies
        run: bun install

      - name: Build Language Server
        run: bun run build

      - name: Package Language Server
        run: bun run pack:server
      
      - name: Publish Language Server
        run: bun run publish:server
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_LSP_SERVER_TOKEN }}
